import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { useEffect, useMemo, useState } from "react";
import { Activity, AlertTriangle, Ambulance, BarChart3, Bell, Bookmark, ChevronRight, Fuel, GitBranch, Heart, LogOut, Map as MapIcon, MapPinned, Menu, Moon, Navigation, ParkingCircle, Route as RouteIcon, Search, Settings, Shield, Sparkles, Sun, Trash2, Users, X, Zap } from "lucide-react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { AnimatePresence, motion } from "motion/react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { findRoute, type Algorithm, type GraphNode, type GraphRoad, type OptimizeFor, type RouteResult } from "@/lib/graph";
import { deleteSavedRoute, getTrafficWorkspace, recordRouteSearch, saveRoute } from "@/lib/traffic.functions";

export const Route = createFileRoute("/_authenticated/dashboard")({
  head: () => ({ meta: [{ title: "Traffic Control Center — CityNav" }, { name: "description", content: "Analyze city traffic and compare graph-powered routes." }] }),
  component: Dashboard,
});

type View = "map" | "analytics" | "saved" | "emergency" | "admin";
const trafficChart = [{ t: "06:00", flow: 36 }, { t: "09:00", flow: 82 }, { t: "12:00", flow: 61 }, { t: "15:00", flow: 68 }, { t: "18:00", flow: 94 }, { t: "21:00", flow: 48 }];

function Dashboard() {
  const queryClient = useQueryClient(); const navigate = useNavigate();
  const fetchWorkspace = useServerFn(getTrafficWorkspace); const record = useServerFn(recordRouteSearch); const save = useServerFn(saveRoute); const remove = useServerFn(deleteSavedRoute);
  const { data, isLoading, error } = useQuery({ queryKey: ["traffic-workspace"], queryFn: () => fetchWorkspace() });
  const [view, setView] = useState<View>("map"); const [mobileOpen, setMobileOpen] = useState(false); const [dark, setDark] = useState(true);
  const [source, setSource] = useState(""); const [destination, setDestination] = useState(""); const [algorithm, setAlgorithm] = useState<Algorithm>("dijkstra"); const [optimize, setOptimize] = useState<OptimizeFor>("time");
  const [result, setResult] = useState<RouteResult | null>(null); const [emergency, setEmergency] = useState(false); const [routeName, setRouteName] = useState("");
  useEffect(() => { document.documentElement.classList.toggle("dark", dark); }, [dark]);
  useEffect(() => { if (data?.nodes.length && !source) { setSource(data.nodes[0].id); setDestination(data.nodes[data.nodes.length - 1].id); } }, [data, source]);
  const nodes = (data?.nodes ?? []) as GraphNode[]; const roads = (data?.roads ?? []) as GraphRoad[];
  const nodeMap = useMemo(() => new Map(nodes.map((node) => [node.id, node])), [nodes]);
  const calculate = () => {
    if (!source || !destination || source === destination) return;
    const route = findRoute(nodes, roads, source, destination, algorithm, emergency ? "time" : optimize);
    setResult(route);
    if (route) record({ data: { sourceId: source, destinationId: destination, algorithm, distance: route.distance, time: route.time, junctionCount: route.path.length, fuel: route.fuel, traffic: route.traffic, path: route.path } }).then(() => queryClient.invalidateQueries({ queryKey: ["traffic-workspace"] }));
  };
  const saveMutation = useMutation({ mutationFn: () => result ? save({ data: { sourceId: source, destinationId: destination, algorithm, distance: result.distance, time: result.time, junctionCount: result.path.length, fuel: result.fuel, traffic: result.traffic, path: result.path, name: routeName.trim() || `${nodeMap.get(source)?.name} → ${nodeMap.get(destination)?.name}`, favorite: false } }) : Promise.resolve({ ok: false }), onSuccess: () => { setRouteName(""); queryClient.invalidateQueries({ queryKey: ["traffic-workspace"] }); } });
  const deleteMutation = useMutation({ mutationFn: (id: string) => remove({ data: { id } }), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["traffic-workspace"] }) });
  const signOut = async () => { await queryClient.cancelQueries(); queryClient.clear(); await supabase.auth.signOut(); navigate({ to: "/auth", replace: true }); };
  const items: Array<{ id: View; label: string; icon: typeof MapIcon; admin?: boolean }> = [{ id: "map", label: "City map", icon: MapIcon }, { id: "analytics", label: "Analytics", icon: BarChart3 }, { id: "saved", label: "Saved routes", icon: Bookmark }, { id: "emergency", label: "Emergency", icon: Ambulance }, { id: "admin", label: "Admin panel", icon: Shield, admin: true }];
  if (isLoading) return <div className="grid min-h-screen place-items-center bg-background"><div className="text-center"><Navigation className="mx-auto size-10 animate-pulse text-primary"/><p className="mt-3 text-sm text-muted-foreground">Loading city graph…</p></div></div>;
  if (error || !data) return <div className="grid min-h-screen place-items-center bg-background p-4"><div className="glass-panel rounded-2xl p-8 text-center"><AlertTriangle className="mx-auto text-danger"/><h1 className="mt-3 text-xl">Workspace unavailable</h1><p className="text-muted-foreground">Please refresh and try again.</p></div></div>;
  return <div className="flex min-h-screen bg-background text-foreground">
    <aside className={`${mobileOpen ? "translate-x-0" : "-translate-x-full"} fixed inset-y-0 left-0 z-50 flex w-72 flex-col border-r border-border bg-card p-4 transition-transform lg:sticky lg:translate-x-0`}>
      <div className="flex h-12 items-center justify-between px-2"><div className="flex items-center gap-3 font-display text-lg font-semibold"><span className="grid size-9 place-items-center rounded-xl bg-primary text-primary-foreground"><MapPinned className="size-5"/></span>CityNav</div><Button className="lg:hidden" variant="ghost" size="icon" onClick={() => setMobileOpen(false)}><X/></Button></div>
      <nav className="mt-8 space-y-1">{items.filter((item) => !item.admin || data.isAdmin).map(({id,label,icon:Icon})=><Button key={id} variant={view === id ? "secondary" : "ghost"} className="h-11 w-full justify-start" onClick={() => { setView(id); setMobileOpen(false); }}><Icon/>{label}{view === id && <ChevronRight className="ml-auto"/>}</Button>)}</nav>
      <div className="mt-8"><p className="px-3 text-[10px] font-bold uppercase tracking-[.2em] text-muted-foreground">Graph status</p><div className="mt-3 space-y-2 rounded-2xl bg-muted/60 p-4 text-sm"><div className="flex justify-between"><span className="text-muted-foreground">Nodes</span><b>{nodes.length}</b></div><div className="flex justify-between"><span className="text-muted-foreground">Edges</span><b>{roads.length}</b></div><div className="flex justify-between"><span className="text-muted-foreground">Network</span><span className="text-success">● Online</span></div></div></div>
      <div className="mt-auto space-y-2"><Button variant="ghost" className="w-full justify-start" onClick={() => setDark(!dark)}>{dark ? <Sun/> : <Moon/>}{dark ? "Light mode" : "Dark mode"}</Button><Button variant="ghost" className="w-full justify-start text-danger" onClick={signOut}><LogOut/>Sign out</Button></div>
    </aside>
    {mobileOpen && <div className="fixed inset-0 z-40 bg-map/70 lg:hidden" onClick={() => setMobileOpen(false)}/>} 
    <main className="min-w-0 flex-1">
      <header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-border bg-background/80 px-4 backdrop-blur-xl sm:px-6"><div className="flex items-center gap-3"><Button variant="ghost" size="icon" className="lg:hidden" onClick={() => setMobileOpen(true)}><Menu/></Button><div><h1 className="font-display font-semibold">{items.find((item) => item.id === view)?.label}</h1><p className="hidden text-xs text-muted-foreground sm:block">Live graph operations · Updated now</p></div></div><div className="flex items-center gap-2"><Button variant="glass" size="icon" aria-label="Notifications"><Bell/></Button><div className="hidden text-right sm:block"><p className="text-sm font-semibold">{data.profile?.display_name ?? "City Navigator"}</p><p className="text-xs text-muted-foreground">{data.isAdmin ? "System administrator" : "Traffic analyst"}</p></div><div className="grid size-9 place-items-center rounded-full bg-primary/15 font-semibold text-primary">{(data.profile?.display_name ?? "C").charAt(0)}</div></div></header>
      <AnimatePresence mode="wait"><motion.div key={view} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} className="p-4 sm:p-6">{view === "map" && <MapWorkspace nodes={nodes} roads={roads} source={source} destination={destination} setSource={setSource} setDestination={setDestination} algorithm={algorithm} setAlgorithm={setAlgorithm} optimize={optimize} setOptimize={setOptimize} result={result} calculate={calculate} nodeMap={nodeMap} emergency={emergency} setEmergency={setEmergency} routeName={routeName} setRouteName={setRouteName} saveRoute={() => saveMutation.mutate()} saving={saveMutation.isPending}/>} {view === "analytics" && <Analytics data={data}/>} {view === "saved" && <SavedRoutes data={data} nodeMap={nodeMap} onDelete={(id) => deleteMutation.mutate(id)}/>} {view === "emergency" && <Emergency onLaunch={() => { setEmergency(true); setView("map"); }}/>} {view === "admin" && <Admin data={data}/>}</motion.div></AnimatePresence>
    </main>
  </div>;
}

function MapWorkspace(props: { nodes: GraphNode[]; roads: GraphRoad[]; source: string; destination: string; setSource:(v:string)=>void; setDestination:(v:string)=>void; algorithm:Algorithm; setAlgorithm:(v:Algorithm)=>void; optimize:OptimizeFor; setOptimize:(v:OptimizeFor)=>void; result:RouteResult|null; calculate:()=>void; nodeMap:Map<string,GraphNode>; emergency:boolean; setEmergency:(v:boolean)=>void; routeName:string; setRouteName:(v:string)=>void; saveRoute:()=>void; saving:boolean }) {
  const selectedRoads = new Set<string>(); if (props.result) for (let i=0;i<props.result.path.length-1;i++) props.roads.filter((r)=>(r.start_node===props.result?.path[i]&&r.end_node===props.result?.path[i+1])||(r.bidirectional&&r.end_node===props.result?.path[i]&&r.start_node===props.result?.path[i+1])).forEach((r)=>selectedRoads.add(r.id));
  const xs=props.nodes.map(n=>n.longitude), ys=props.nodes.map(n=>n.latitude); const minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys); const pos=(n:GraphNode)=>({x:55+((n.longitude-minX)/(maxX-minX))*790,y:520-45-((n.latitude-minY)/(maxY-minY))*420});
  return <div className="grid gap-5 xl:grid-cols-[360px_1fr]">
    <section className="glass-panel rounded-2xl p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-primary">Route finder</p><h2 className="mt-1 text-xl font-semibold">Plan a journey</h2></div><Button variant={props.emergency ? "destructive" : "glass"} size="icon" onClick={()=>props.setEmergency(!props.emergency)} aria-label="Emergency mode"><Ambulance/></Button></div><div className="mt-6 space-y-4"><label className="block text-xs font-semibold text-muted-foreground">SOURCE<Select value={props.source} onValueChange={props.setSource}><SelectTrigger className="mt-1 h-11"><SelectValue/></SelectTrigger><SelectContent>{props.nodes.map(n=><SelectItem key={n.id} value={n.id}>{n.name}</SelectItem>)}</SelectContent></Select></label><label className="block text-xs font-semibold text-muted-foreground">DESTINATION<Select value={props.destination} onValueChange={props.setDestination}><SelectTrigger className="mt-1 h-11"><SelectValue/></SelectTrigger><SelectContent>{props.nodes.map(n=><SelectItem key={n.id} value={n.id}>{n.name}</SelectItem>)}</SelectContent></Select></label><div className="grid grid-cols-2 gap-3"><label className="text-xs font-semibold text-muted-foreground">ALGORITHM<Select value={props.algorithm} onValueChange={(v)=>props.setAlgorithm(v as Algorithm)}><SelectTrigger className="mt-1 h-11"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="dijkstra">Dijkstra</SelectItem><SelectItem value="astar">A* Search</SelectItem><SelectItem value="bfs">BFS</SelectItem><SelectItem value="dfs">DFS</SelectItem></SelectContent></Select></label><label className="text-xs font-semibold text-muted-foreground">OPTIMIZE<Select value={props.optimize} onValueChange={(v)=>props.setOptimize(v as OptimizeFor)}><SelectTrigger className="mt-1 h-11"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="time">Travel time</SelectItem><SelectItem value="distance">Distance</SelectItem></SelectContent></Select></label></div><Button variant={props.emergency ? "destructive" : "hero"} size="xl" className="w-full" onClick={props.calculate}><Navigation/>{props.emergency ? "Find priority path" : "Calculate route"}</Button></div>
      {props.result && <motion.div initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className="mt-6 border-t border-border pt-5"><div className="grid grid-cols-2 gap-3">{[[RouteIcon,`${props.result.distance.toFixed(1)} km`,`Distance`],[Activity,`${Math.round(props.result.time)} min`,`Est. time`],[GitBranch,`${props.result.path.length}`,`Junctions`],[Fuel,`${props.result.fuel.toFixed(2)} L`,`Fuel`]].map(([Icon,value,label])=><div key={String(label)} className="rounded-xl bg-muted/60 p-3"><Icon className="size-4 text-primary"/><b className="mt-2 block">{String(value)}</b><small className="text-muted-foreground">{String(label)}</small></div>)}</div><div className="mt-3 rounded-xl border border-border p-3"><div className="flex items-center justify-between text-xs"><span className="text-muted-foreground">Visited nodes</span><b>{props.result.visited.length} / {props.nodes.length}</b></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{width:`${props.result.visited.length/props.nodes.length*100}%`}}/></div></div><div className="mt-3 flex gap-2"><Input placeholder="Route name" value={props.routeName} onChange={e=>props.setRouteName(e.target.value)} maxLength={80}/><Button variant="glass" size="icon" onClick={props.saveRoute} disabled={props.saving} aria-label="Save route"><Bookmark/></Button></div></motion.div>}
    </section>
    <section className="glass-panel relative min-h-[580px] overflow-hidden rounded-2xl bg-map"><div className="absolute left-4 top-4 z-10 flex gap-2"><span className="rounded-full bg-card/80 px-3 py-1 text-xs backdrop-blur">● {props.roads.filter(r=>r.traffic_level==='heavy').length} heavy roads</span><span className="rounded-full bg-card/80 px-3 py-1 text-xs backdrop-blur">{props.algorithm.toUpperCase()}</span></div><svg viewBox="0 0 900 520" className="absolute inset-0 size-full" aria-label="Interactive weighted city graph map"><g>{props.roads.map(r=>{const a=props.nodeMap.get(r.start_node),b=props.nodeMap.get(r.end_node);if(!a||!b)return null;const p1=pos(a),p2=pos(b);const active=selectedRoads.has(r.id);const color=active?'var(--primary)':r.traffic_level==='heavy'?'var(--danger)':r.traffic_level==='medium'?'var(--warning)':'var(--success)';return <g key={r.id}><line x1={p1.x} y1={p1.y} x2={p2.x} y2={p2.y} stroke={color} strokeWidth={active?7:3} strokeOpacity={active?1:.55} strokeDasharray={active?'12 8':undefined} className={active?'route-flow':undefined}/><text x={(p1.x+p2.x)/2} y={(p1.y+p2.y)/2-5} textAnchor="middle" fill="var(--muted-foreground)" fontSize="10">{Number(r.distance_km).toFixed(1)}km</text></g>})}</g><g>{props.nodes.map(n=>{const p=pos(n);const active=props.result?.path.includes(n.id);return <g key={n.id} onClick={()=>!props.source?props.setSource(n.id):props.setDestination(n.id)} className="cursor-pointer"><circle cx={p.x} cy={p.y} r={active?10:7} fill={active?'var(--primary)':'var(--foreground)'} stroke="var(--map)" strokeWidth="4"/><text x={p.x} y={p.y+22} textAnchor="middle" fill="var(--foreground)" fontSize="11" fontWeight="600">{n.name}</text></g>})}</g></svg><div className="absolute bottom-4 left-4 flex flex-wrap gap-3 rounded-xl bg-card/80 px-4 py-2 text-[10px] backdrop-blur"><span className="text-success">● Low</span><span className="text-warning">● Medium</span><span className="text-danger">● Heavy</span><span className="text-primary">● Selected path</span></div></section>
  </div>;
}

function Analytics({data}:{data:Awaited<ReturnType<typeof getTrafficWorkspace>>}) { const stats=[[Search,data.searches.length,"Routes searched"],[Bookmark,data.saved.length,"Saved routes"],[Heart,data.favorites.length,"Favorite places"],[AlertTriangle,data.alerts.length,"Traffic alerts"]] as const; return <div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(([Icon,v,l])=><div key={l} className="glass-panel rounded-2xl p-5"><div className="flex items-center justify-between"><span className="grid size-10 place-items-center rounded-xl bg-primary/10 text-primary"><Icon/></span><span className="text-xs text-success">Live</span></div><b className="mt-5 block font-display text-3xl">{v}</b><p className="text-sm text-muted-foreground">{l}</p></div>)}</div><div className="mt-5 grid gap-5 xl:grid-cols-[1.5fr_1fr]"><section className="glass-panel rounded-2xl p-6"><h2 className="text-xl font-semibold">Daily traffic flow</h2><p className="text-sm text-muted-foreground">Estimated network utilization by hour</p><div className="mt-6 h-72"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trafficChart}><defs><linearGradient id="flow" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--primary)" stopOpacity={.55}/><stop offset="100%" stopColor="var(--primary)" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="t" stroke="var(--muted-foreground)"/><YAxis stroke="var(--muted-foreground)"/><Tooltip contentStyle={{background:"var(--card)",border:"1px solid var(--border)",borderRadius:12}}/><Area type="monotone" dataKey="flow" stroke="var(--primary)" fill="url(#flow)" strokeWidth={3}/></AreaChart></ResponsiveContainer></div></section><section className="glass-panel rounded-2xl p-6"><h2 className="text-xl font-semibold">Active alerts</h2><div className="mt-5 space-y-3">{data.alerts.map(a=><div key={a.id} className="rounded-xl bg-muted/55 p-4"><div className="flex items-center gap-2"><span className={a.severity==='heavy'?'text-danger':'text-warning'}>●</span><b className="text-sm">{a.title}</b></div><p className="mt-1 text-xs leading-5 text-muted-foreground">{a.description}</p></div>)}</div></section></div></div> }
function SavedRoutes({data,nodeMap,onDelete}:{data:Awaited<ReturnType<typeof getTrafficWorkspace>>;nodeMap:Map<string,GraphNode>;onDelete:(id:string)=>void}) { return <div><div className="mb-6"><h2 className="text-2xl font-semibold">Your route library</h2><p className="text-muted-foreground">Reuse, compare and favorite frequent journeys.</p></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.saved.length?data.saved.map(r=><article key={r.id} className="glass-panel rounded-2xl p-5"><div className="flex items-start justify-between"><span className="grid size-10 place-items-center rounded-xl bg-primary/10 text-primary"><RouteIcon/></span><Button variant="ghost" size="icon" onClick={()=>onDelete(r.id)} aria-label="Delete route"><Trash2/></Button></div><h3 className="mt-5 text-lg font-semibold">{r.name}</h3><p className="mt-1 text-sm text-muted-foreground">{nodeMap.get(r.source_id)?.name} → {nodeMap.get(r.destination_id)?.name}</p><div className="mt-5 flex gap-5 text-sm"><span><b>{Number(r.distance_km).toFixed(1)}</b> km</span><span><b>{Math.round(Number(r.travel_time_minutes))}</b> min</span><span className="uppercase text-primary">{r.algorithm}</span></div></article>):<div className="glass-panel rounded-2xl p-10 text-center md:col-span-2"><Bookmark className="mx-auto size-9 text-muted-foreground"/><h3 className="mt-3 font-semibold">No saved routes yet</h3><p className="text-sm text-muted-foreground">Calculate a route on the city map and save it here.</p></div>}</div></div> }
function Emergency({onLaunch}:{onLaunch:()=>void}) { return <div><div className="mb-6"><p className="text-xs font-bold uppercase tracking-widest text-danger">Priority response</p><h2 className="mt-2 text-3xl font-semibold">Emergency routing center</h2></div><div className="grid gap-4 md:grid-cols-3">{[[Ambulance,"Ambulance","Hospital priority"],[Activity,"Fire service","Hazard avoidance"],[Shield,"Police","Rapid response"]].map(([Icon,title,text])=><article key={String(title)} className="glass-panel rounded-2xl p-6"><Icon className="size-9 text-danger"/><h3 className="mt-6 text-xl font-semibold">{String(title)}</h3><p className="text-sm text-muted-foreground">{String(text)}</p><Button variant="destructive" className="mt-8 w-full" onClick={onLaunch}>Launch priority route</Button></article>)}</div><section className="glass-panel mt-5 rounded-2xl p-6"><h3 className="text-lg font-semibold">Emergency path logic</h3><div className="mt-4 grid gap-4 sm:grid-cols-3">{[[Zap,"Minimize weighted time"],[AlertTriangle,"Avoid heavy congestion"],[Navigation,"Prioritize clear corridors"]].map(([Icon,t])=><div key={String(t)} className="flex items-center gap-3 rounded-xl bg-muted/50 p-4"><Icon className="text-primary"/><span className="text-sm">{String(t)}</span></div>)}</div></section></div> }
function Admin({data}:{data:Awaited<ReturnType<typeof getTrafficWorkspace>>}) { return <div><div className="mb-6"><h2 className="text-2xl font-semibold">Network administration</h2><p className="text-muted-foreground">Manage graph topology and traffic operations.</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[[MapPinned,data.nodes.length,"Intersections"],[RouteIcon,data.roads.length,"Roads"],[Users,"—","Users"],[AlertTriangle,data.alerts.length,"Alerts"]].map(([Icon,v,l])=><div key={String(l)} className="glass-panel rounded-2xl p-5"><Icon className="text-primary"/><b className="mt-6 block text-3xl">{String(v)}</b><span className="text-sm text-muted-foreground">{String(l)}</span></div>)}</div><div className="glass-panel mt-5 overflow-x-auto rounded-2xl p-6"><div className="mb-5 flex items-center justify-between"><h3 className="text-lg font-semibold">Road network</h3><Button variant="hero">Add road</Button></div><table className="w-full min-w-[650px] text-left text-sm"><thead className="text-xs uppercase tracking-wider text-muted-foreground"><tr><th className="pb-3">Road</th><th>Distance</th><th>Base time</th><th>Traffic</th><th>Weight</th></tr></thead><tbody>{data.roads.map(r=><tr key={r.id} className="border-t border-border"><td className="py-4 font-semibold">{r.name}</td><td>{Number(r.distance_km).toFixed(1)} km</td><td>{Number(r.base_time_minutes)} min</td><td className="capitalize">{r.traffic_level}</td><td>{Number(r.traffic_weight).toFixed(1)}×</td></tr>)}</tbody></table></div></div> }