import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { lazy, Suspense, useEffect, useMemo, useState } from "react";
import { Activity, AlertTriangle, BarChart3, Bell, Bookmark, Building2, CarFront, ChevronRight, Clock3, Gauge, LogOut, Map as MapIcon, MapPinned, Menu, Navigation, Route as RouteIcon, Search, Shield, Trash2, Users, X } from "lucide-react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { AnimatePresence, motion } from "motion/react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import type { GraphNode, GraphRoad, RouteResult } from "@/lib/graph";
import { calculateBestRoute, deleteSavedRoute, getTrafficWorkspace, recordRouteSearch, saveRoute } from "@/lib/traffic.functions";

const TrafficMap = lazy(() => import("@/components/traffic-map").then((module) => ({ default: module.TrafficMap })));

export const Route = createFileRoute("/_authenticated/dashboard")({
  head: () => ({ meta: [{ title: "UrbanFlow Navigation | Live Traffic" }, { name: "description", content: "Plan faster journeys with live traffic intelligence and route guidance." }] }),
  component: Dashboard,
});

type View = "map" | "analytics" | "saved" | "alerts" | "admin";
const trafficChart = [{ t: "06:00", flow: 34 }, { t: "09:00", flow: 82 }, { t: "12:00", flow: 58 }, { t: "15:00", flow: 69 }, { t: "18:00", flow: 92 }, { t: "21:00", flow: 45 }];

function Dashboard() {
  const queryClient = useQueryClient();
  const navigate = useNavigate();
  const fetchWorkspace = useServerFn(getTrafficWorkspace);
  const calculateRoute = useServerFn(calculateBestRoute);
  const record = useServerFn(recordRouteSearch);
  const save = useServerFn(saveRoute);
  const remove = useServerFn(deleteSavedRoute);
  const { data, isLoading, error } = useQuery({ queryKey: ["traffic-workspace"], queryFn: () => fetchWorkspace() });
  const [view, setView] = useState<View>("map");
  const [mobileOpen, setMobileOpen] = useState(false);
  const [source, setSource] = useState("");
  const [destination, setDestination] = useState("");
  const [preference, setPreference] = useState<"fastest" | "shortest">("fastest");
  const [result, setResult] = useState<RouteResult | null>(null);
  const [routeName, setRouteName] = useState("");
  useEffect(() => { document.documentElement.classList.add("dark"); }, []);
  useEffect(() => { if (data?.nodes.length && !source) { setSource(data.nodes[0].id); setDestination(data.nodes[data.nodes.length - 1].id); } }, [data, source]);
  const nodes = (data?.nodes ?? []) as GraphNode[];
  const roads = (data?.roads ?? []) as GraphRoad[];
  const nodeMap = useMemo(() => new Map(nodes.map((node) => [node.id, node])), [nodes]);
  const routeMutation = useMutation({
    mutationFn: () => calculateRoute({ data: { sourceId: source, destinationId: destination, preference } }),
    onSuccess: (route) => {
      setResult(route);
      record({ data: { sourceId: source, destinationId: destination, algorithm: route.algorithm, distance: route.distance, time: route.time, junctionCount: route.path.length, fuel: route.fuel, traffic: route.traffic, path: route.path } }).then(() => queryClient.invalidateQueries({ queryKey: ["traffic-workspace"] }));
    },
  });
  const saveMutation = useMutation({ mutationFn: () => result ? save({ data: { sourceId: source, destinationId: destination, algorithm: result.algorithm, distance: result.distance, time: result.time, junctionCount: result.path.length, fuel: result.fuel, traffic: result.traffic, path: result.path, name: routeName.trim() || `${nodeMap.get(source)?.name} → ${nodeMap.get(destination)?.name}`, favorite: false } }) : Promise.resolve({ ok: false }), onSuccess: () => { setRouteName(""); queryClient.invalidateQueries({ queryKey: ["traffic-workspace"] }); } });
  const deleteMutation = useMutation({ mutationFn: (id: string) => remove({ data: { id } }), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["traffic-workspace"] }) });
  const signOut = async () => { await queryClient.cancelQueries(); queryClient.clear(); await supabase.auth.signOut(); navigate({ to: "/auth", replace: true }); };
  const items: Array<{ id: View; label: string; icon: typeof MapIcon; admin?: boolean }> = [
    { id: "map", label: "Live map", icon: MapIcon }, { id: "analytics", label: "Traffic insights", icon: BarChart3 }, { id: "saved", label: "Saved routes", icon: Bookmark }, { id: "alerts", label: "Alerts", icon: AlertTriangle }, { id: "admin", label: "Admin console", icon: Shield, admin: true },
  ];
  if (isLoading) return <LoadingScreen />;
  if (error || !data) return <div className="grid min-h-screen place-items-center bg-background p-4"><div className="glass-panel rounded-2xl p-8 text-center"><AlertTriangle className="mx-auto text-danger"/><h1 className="mt-3 text-xl">Navigation unavailable</h1><p className="text-muted-foreground">Please refresh and try again.</p></div></div>;
  return <div className="flex min-h-screen bg-background text-foreground">
    <aside className={`${mobileOpen ? "translate-x-0" : "-translate-x-full"} fixed inset-y-0 left-0 z-[1000] flex w-72 flex-col border-r border-sidebar-border bg-sidebar p-4 transition-transform lg:sticky lg:translate-x-0`}>
      <div className="flex h-14 items-center justify-between px-2"><div className="flex items-center gap-3 font-display text-lg font-semibold"><LogoMark/>UrbanFlow</div><Button className="lg:hidden" variant="ghost" size="icon" onClick={() => setMobileOpen(false)}><X/></Button></div>
      <nav className="mt-8 space-y-1">{items.filter((item) => !item.admin || data.isAdmin).map(({id,label,icon:Icon})=><Button key={id} variant={view === id ? "secondary" : "ghost"} className="h-11 w-full justify-start rounded-xl" onClick={() => { setView(id); setMobileOpen(false); }}><Icon/>{label}{view === id && <ChevronRight className="ml-auto"/>}</Button>)}</nav>
      <div className="mt-8 rounded-2xl border border-border bg-muted/40 p-4"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-muted-foreground">City status</p><div className="mt-4 space-y-3 text-sm"><div className="flex justify-between"><span className="text-muted-foreground">Road flow</span><b>87%</b></div><div className="flex justify-between"><span className="text-muted-foreground">Active alerts</span><b>{data.alerts.length}</b></div><div className="flex items-center gap-2 border-t border-border pt-3 text-xs text-success"><span className="size-2 animate-pulse rounded-full bg-success"/>Live data connected</div></div></div>
      <div className="mt-auto"><Button variant="ghost" className="w-full justify-start text-danger" onClick={signOut}><LogOut/>Sign out</Button></div>
    </aside>
    {mobileOpen && <div className="fixed inset-0 z-[900] bg-background/80 lg:hidden" onClick={() => setMobileOpen(false)}/>} 
    <main className="min-w-0 flex-1">
      <header className="sticky top-0 z-[800] grid h-16 grid-cols-[minmax(0,1fr)_auto] items-center border-b border-border bg-background/85 px-4 backdrop-blur-xl sm:px-6"><div className="flex min-w-0 items-center gap-3"><Button variant="ghost" size="icon" className="shrink-0 lg:hidden" onClick={() => setMobileOpen(true)}><Menu/></Button><div className="min-w-0"><h1 className="truncate font-display font-semibold">{items.find((item) => item.id === view)?.label}</h1><p className="hidden text-xs text-muted-foreground sm:block">City-wide traffic intelligence · Live</p></div></div><div className="flex items-center gap-2"><Button variant="glass" size="icon" aria-label="Notifications" onClick={() => setView("alerts")} className="relative"><Bell/><span className="absolute right-1 top-1 size-2 rounded-full bg-primary"/></Button><div className="hidden text-right sm:block"><p className="text-sm font-semibold">{data.profile?.display_name ?? "Urban Navigator"}</p><p className="text-xs text-muted-foreground">{data.isAdmin ? "System administrator" : "City traveler"}</p></div><div className="grid size-9 shrink-0 place-items-center rounded-full bg-primary/15 font-semibold text-primary">{(data.profile?.display_name ?? "U").charAt(0)}</div></div></header>
      <AnimatePresence mode="wait"><motion.div key={view} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} className="p-3 sm:p-5">{view === "map" && <MapWorkspace nodes={nodes} roads={roads} source={source} destination={destination} setSource={setSource} setDestination={setDestination} preference={preference} setPreference={setPreference} result={result} calculate={() => routeMutation.mutate()} calculating={routeMutation.isPending} routeError={routeMutation.error?.message} routeName={routeName} setRouteName={setRouteName} saveRoute={() => saveMutation.mutate()} saving={saveMutation.isPending}/>} {view === "analytics" && <Analytics data={data}/>} {view === "saved" && <SavedRoutes data={data} nodeMap={nodeMap} onDelete={(id) => deleteMutation.mutate(id)}/>} {view === "alerts" && <Alerts data={data}/>} {view === "admin" && <Admin data={data}/>}</motion.div></AnimatePresence>
    </main>
  </div>;
}

function LogoMark() { return <span className="grid size-9 place-items-center rounded-xl bg-gradient-to-br from-primary to-primary/60 text-primary-foreground shadow-[var(--shadow-glow)]"><Navigation className="size-5 -rotate-12"/></span>; }
function LoadingScreen() { return <div className="min-h-screen bg-background p-5"><div className="mx-auto grid max-w-7xl animate-pulse gap-4 lg:grid-cols-[320px_1fr]"><div className="h-[620px] rounded-3xl bg-muted"/><div className="h-[620px] rounded-3xl bg-muted"/></div></div>; }

function MapWorkspace(props: { nodes: GraphNode[]; roads: GraphRoad[]; source: string; destination: string; setSource:(v:string)=>void; setDestination:(v:string)=>void; preference:"fastest"|"shortest"; setPreference:(v:"fastest"|"shortest")=>void; result:RouteResult|null; calculate:()=>void; calculating:boolean; routeError?:string; routeName:string; setRouteName:(v:string)=>void; saveRoute:()=>void; saving:boolean }) {
  const destinationName = props.nodes.find((node) => node.id === props.destination)?.name;
  const arrival = props.result ? new Date(Date.now() + props.result.time * 60000).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) : "—";
  return <div className="grid min-h-[calc(100vh-6.5rem)] gap-4 xl:grid-cols-[360px_1fr]">
    <section className="glass-panel rounded-3xl p-5 sm:p-6"><p className="text-xs font-bold uppercase tracking-[.18em] text-primary">Smart route planner</p><h2 className="mt-2 text-2xl font-semibold">Where are you going?</h2><p className="mt-1 text-sm text-muted-foreground">Live conditions are applied automatically.</p>
      <div className="mt-7 space-y-4"><label className="block text-xs font-semibold text-muted-foreground">STARTING POINT<Select value={props.source} onValueChange={props.setSource}><SelectTrigger className="mt-2 h-12 rounded-xl"><SelectValue/></SelectTrigger><SelectContent>{props.nodes.map(n=><SelectItem key={n.id} value={n.id}>{n.name}</SelectItem>)}</SelectContent></Select></label><label className="block text-xs font-semibold text-muted-foreground">DESTINATION<Select value={props.destination} onValueChange={props.setDestination}><SelectTrigger className="mt-2 h-12 rounded-xl"><SelectValue/></SelectTrigger><SelectContent>{props.nodes.map(n=><SelectItem key={n.id} value={n.id}>{n.name}</SelectItem>)}</SelectContent></Select></label><label className="block text-xs font-semibold text-muted-foreground">ROUTE PREFERENCE<Select value={props.preference} onValueChange={(value)=>props.setPreference(value as "fastest"|"shortest")}><SelectTrigger className="mt-2 h-12 rounded-xl"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="fastest">Fastest arrival</SelectItem><SelectItem value="shortest">Shortest distance</SelectItem></SelectContent></Select></label><Button variant="hero" size="xl" className="w-full rounded-xl" onClick={props.calculate} disabled={props.calculating || !props.source || props.source === props.destination}><Navigation/>{props.calculating ? "Finding your best route…" : "Plan best route"}</Button>{props.routeError && <p className="text-sm text-danger">{props.routeError}</p>}</div>
      {props.result && <motion.div initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className="mt-6 border-t border-border pt-5"><div className="flex items-start justify-between"><div><p className="text-xs text-muted-foreground">Best route to {destinationName}</p><b className="mt-1 block text-3xl text-primary">{Math.round(props.result.time)} min</b></div><span className={`rounded-full px-3 py-1 text-xs font-semibold ${props.result.traffic === "heavy" ? "bg-danger/15 text-danger" : "bg-success/15 text-success"}`}>{props.result.traffic === "heavy" ? "Heavy traffic" : props.result.traffic === "medium" ? "Moderate traffic" : "Clear traffic"}</span></div><div className="mt-5 grid grid-cols-3 gap-2">{[[`${props.result.distance.toFixed(1)} km`,`Distance`],[arrival,"Arrival"],[`${props.result.distance.toFixed(1)} km`,`Remaining`]].map(([value,label])=><div key={label} className="rounded-xl bg-muted/60 p-3"><b className="block text-sm">{value}</b><small className="text-muted-foreground">{label}</small></div>)}</div><div className="mt-3 flex gap-2"><Input placeholder="Name this route" value={props.routeName} onChange={e=>props.setRouteName(e.target.value)} maxLength={80}/><Button variant="glass" size="icon" onClick={props.saveRoute} disabled={props.saving} aria-label="Save route"><Bookmark/></Button></div></motion.div>}
    </section>
    <section className="relative min-h-[560px] overflow-hidden rounded-3xl border border-border bg-map"><Suspense fallback={<div className="grid size-full place-items-center text-sm text-muted-foreground">Loading live map…</div>}><TrafficMap locations={props.nodes} roads={props.roads} route={props.result?.path ?? []}/></Suspense><div className="pointer-events-none absolute left-4 top-4 z-[500] flex flex-wrap gap-2"><span className="rounded-full border border-border bg-card/90 px-3 py-2 text-xs backdrop-blur-xl"><span className="text-success">●</span> Live traffic</span><span className="rounded-full border border-border bg-card/90 px-3 py-2 text-xs backdrop-blur-xl">{props.roads.filter(r=>r.traffic_level==='heavy').length} congested roads</span></div>{props.result && <div className="absolute bottom-4 left-4 right-4 z-[500] grid grid-cols-[minmax(0,1fr)_auto] items-center gap-4 rounded-2xl border border-border bg-card/90 p-4 backdrop-blur-xl sm:left-auto sm:w-80"><div className="min-w-0"><p className="truncate text-xs text-muted-foreground">Continue toward {destinationName}</p><b className="text-lg">Arrival {arrival}</b></div><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-primary text-primary-foreground"><RouteIcon/></span></div>}</section>
  </div>;
}

type Workspace = Awaited<ReturnType<typeof getTrafficWorkspace>>;
function Analytics({data}:{data:Workspace}) { const avg = data.searches.length ? Math.round(data.searches.reduce((sum,item)=>sum+Number(item.travel_time_minutes),0)/data.searches.length) : 0; const stats=[[RouteIcon,data.searches.length,"Routes planned"],[Clock3,`${avg} min`,"Average travel time"],[AlertTriangle,data.alerts.length,"Active alerts"],[Bookmark,data.saved.length,"Saved destinations"]] as const; return <div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(([Icon,value,label])=><article key={label} className="glass-panel rounded-2xl p-5"><span className="grid size-10 place-items-center rounded-xl bg-primary/10 text-primary"><Icon/></span><b className="mt-5 block font-display text-3xl">{value}</b><p className="text-sm text-muted-foreground">{label}</p></article>)}</div><div className="mt-5 grid gap-5 xl:grid-cols-[1.5fr_1fr]"><section className="glass-panel rounded-2xl p-6"><h2 className="text-xl font-semibold">Traffic by hour</h2><p className="text-sm text-muted-foreground">Realistic city-wide congestion forecast</p><div className="mt-6 h-72"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trafficChart}><defs><linearGradient id="flow" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--primary)" stopOpacity={.55}/><stop offset="100%" stopColor="var(--primary)" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="t" stroke="var(--muted-foreground)"/><YAxis stroke="var(--muted-foreground)"/><Tooltip contentStyle={{background:"var(--card)",border:"1px solid var(--border)",borderRadius:12}}/><Area type="monotone" dataKey="flow" stroke="var(--primary)" fill="url(#flow)" strokeWidth={3}/></AreaChart></ResponsiveContainer></div></section><section className="glass-panel rounded-2xl p-6"><h2 className="text-xl font-semibold">Recent activity</h2><div className="mt-5 space-y-4">{data.searches.slice(0,5).map((item)=><div key={item.id} className="flex gap-3 border-b border-border pb-4"><span className="mt-1 size-2 shrink-0 rounded-full bg-primary"/><div><p className="text-sm font-semibold">Journey planned</p><p className="text-xs text-muted-foreground">{Number(item.distance_km).toFixed(1)} km · {Math.round(Number(item.travel_time_minutes))} min</p></div></div>)}</div></section></div></div>; }
function SavedRoutes({data,nodeMap,onDelete}:{data:Workspace;nodeMap:Map<string,GraphNode>;onDelete:(id:string)=>void}) { return <div><div className="mb-6"><h2 className="text-2xl font-semibold">Saved routes</h2><p className="text-muted-foreground">Your frequent journeys, ready when you are.</p></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.saved.length?data.saved.map(route=><article key={route.id} className="glass-panel rounded-2xl p-5 transition-transform hover:-translate-y-1"><div className="flex items-start justify-between"><span className="grid size-10 place-items-center rounded-xl bg-primary/10 text-primary"><RouteIcon/></span><Button variant="ghost" size="icon" onClick={()=>onDelete(route.id)} aria-label="Delete route"><Trash2/></Button></div><h3 className="mt-5 text-lg font-semibold">{route.name}</h3><p className="mt-1 text-sm text-muted-foreground">{nodeMap.get(route.source_id)?.name} → {nodeMap.get(route.destination_id)?.name}</p><div className="mt-5 flex gap-5 text-sm"><span><b>{Number(route.distance_km).toFixed(1)}</b> km</span><span><b>{Math.round(Number(route.travel_time_minutes))}</b> min</span></div></article>):<div className="glass-panel rounded-2xl p-10 text-center md:col-span-2"><Bookmark className="mx-auto size-9 text-muted-foreground"/><h3 className="mt-3 font-semibold">No saved routes yet</h3><p className="text-sm text-muted-foreground">Plan a route on the live map and save it here.</p></div>}</div></div>; }
function Alerts({data}:{data:Workspace}) { const items = data.alerts.map(alert=>({id:alert.id,title:alert.title,message:alert.description,category:alert.alert_type})); return <div><div className="mb-6"><h2 className="text-2xl font-semibold">Traffic intelligence</h2><p className="text-muted-foreground">Closures, accidents, hotspots, and congestion updates.</p></div><div className="grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><section className="glass-panel rounded-2xl p-5"><div className="space-y-3">{items.map(item=><article key={item.id} className="rounded-xl border border-border bg-muted/40 p-4"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-lg bg-warning/15 text-warning"><AlertTriangle/></span><div><h3 className="font-semibold">{item.title}</h3><p className="text-xs capitalize text-muted-foreground">{item.category.replaceAll("_"," ")}</p></div></div><p className="mt-3 text-sm leading-6 text-muted-foreground">{item.message}</p></article>)}</div></section><section className="glass-panel rounded-2xl p-6"><h3 className="text-lg font-semibold">Peak traffic hours</h3><div className="mt-6 space-y-5">{[["Morning rush","08:00–10:00",82],["Lunch traffic","12:00–14:00",61],["Evening rush","17:00–19:30",94]].map(([label,time,value])=><div key={String(label)}><div className="flex justify-between text-sm"><span>{label}</span><span className="text-muted-foreground">{time}</span></div><div className="mt-2 h-2 rounded-full bg-muted"><div className="h-full rounded-full bg-gradient-to-r from-primary to-warning" style={{width:`${value}%`}}/></div></div>)}</div></section></div></div>; }
function Admin({data}:{data:Workspace}) { const stats=[{Icon:Users,value:"Active",label:"User management"},{Icon:Building2,value:data.roads.length,label:"Managed roads"},{Icon:Gauge,value:"87%",label:"Network flow"},{Icon:AlertTriangle,value:data.alerts.length,label:"Open incidents"}]; return <div><div className="mb-6"><p className="text-xs font-bold uppercase tracking-widest text-primary">Operations</p><h2 className="mt-2 text-2xl font-semibold">System overview</h2><p className="text-muted-foreground">Monitor users, roads, traffic, analytics, and reports.</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(({Icon,value,label})=><article key={label} className="glass-panel rounded-2xl p-5"><Icon className="text-primary"/><b className="mt-6 block text-2xl">{value}</b><span className="text-sm text-muted-foreground">{label}</span></article>)}</div><section className="glass-panel mt-5 overflow-x-auto rounded-2xl p-6"><div className="mb-5 flex items-center justify-between"><h3 className="text-lg font-semibold">Road management</h3><Button variant="hero">Create report</Button></div><table className="w-full min-w-[650px] text-left text-sm"><thead className="text-xs uppercase tracking-wider text-muted-foreground"><tr><th className="pb-3">Road</th><th>Distance</th><th>Typical time</th><th>Status</th><th>Flow</th></tr></thead><tbody>{data.roads.map(road=><tr key={road.id} className="border-t border-border"><td className="py-4 font-semibold">{road.name}</td><td>{Number(road.distance_km).toFixed(1)} km</td><td>{Number(road.base_time_minutes)} min</td><td className="capitalize">{road.traffic_level}</td><td>{Math.max(12,Math.round(100/Number(road.traffic_weight)))}%</td></tr>)}</tbody></table></section></div>; }