// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'



export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    let token = '';
    const request = getRequest();
    if (request?.headers) {
      const authHeader = request.headers.get('authorization');
      if (authHeader && authHeader.startsWith('Bearer ')) {
        token = authHeader.replace('Bearer ', '');
      }
    }

    let userId = '00000000-0000-0000-0000-000000000000';
    let supabase: any;

    if (SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY) {
      supabase = createClient<Database>(
        SUPABASE_URL,
        SUPABASE_PUBLISHABLE_KEY,
        {
          global: {
            headers: token ? { Authorization: `Bearer ${token}` } : {},
          },
          auth: {
            storage: undefined,
            persistSession: false,
            autoRefreshToken: false,
          },
        }
      );

      if (token) {
        try {
          const { data, error } = await supabase.auth.getClaims(token);
          if (!error && data?.claims?.sub) {
            userId = data.claims.sub;
          }
        } catch (e) {
          console.warn('Token claims parsing failed:', e);
        }
      }
    } else {
      console.warn('[Supabase] Missing environment variables for requireSupabaseAuth. Falling back to dummy mock client.');
      const createDummyBuilder = () => {
        const dummy = () => proxy;
        dummy.then = (cb: any) => Promise.resolve({ data: null, error: new Error('Supabase unconfigured') }).then(cb);
        const proxy: any = new Proxy(dummy, {
          get(t, p) {
            if (p === 'then') return t.then;
            return proxy;
          }
        });
        return proxy;
      };

      supabase = new Proxy({} as any, {
        get(_, prop) {
          if (prop === 'auth') {
            return {
              getUser: async () => ({ data: { user: null }, error: new Error('Supabase unconfigured') }),
              getSession: async () => ({ data: { session: null }, error: new Error('Supabase unconfigured') }),
              getClaims: async () => ({ data: null, error: new Error('Supabase unconfigured') }),
            };
          }
          return createDummyBuilder();
        }
      });
    }

    return next({
      context: {
        supabase,
        userId,
        claims: token ? {} : null,
      },
    });
  },
);
