// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'



export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    const userId = '00000000-0000-0000-0000-000000000000';
    let supabase: any;

    if (SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY) {
      supabase = createClient<Database>(
        SUPABASE_URL,
        SUPABASE_PUBLISHABLE_KEY,
        {
          auth: {
            storage: undefined,
            persistSession: false,
            autoRefreshToken: false,
          },
        }
      );
    } else {
      console.warn('[Supabase] Missing environment variables for requireSupabaseAuth. Falling back to dummy mock client.');
      const createDummyBuilder = () => {
        const dummy = () => proxy;
        dummy.then = (cb: any) => Promise.resolve({ data: null, error: new Error('Supabase unconfigured') }).then(cb);
        const proxy: any = new Proxy(dummy, {
          get(t, p) {
            if (p === 'then') return t.then;
            return proxy;
          }
        });
        return proxy;
      };

      supabase = new Proxy({} as any, {
        get(_, prop) {
          if (prop === 'auth') {
            return {
              getUser: async () => ({ data: { user: null }, error: new Error('Supabase unconfigured') }),
              getSession: async () => ({ data: { session: null }, error: new Error('Supabase unconfigured') }),
              getClaims: async () => ({ data: null, error: new Error('Supabase unconfigured') }),
            };
          }
          return createDummyBuilder();
        }
      });
    }

    return next({
      context: {
        supabase,
        userId,
        claims: null,
      },
    });
  },
);
